version: '3.8'

services:
  godot-server:
    build: .
    container_name: godot-server # Este nombre es el que busca Cloudflare
    restart: always
    expose:
      - "8910"
    networks:
      - tictactoe_net
    volumes:
      - godot_data:/root/.local/share/godot/app_userdata/

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - tictactoe_net
    depends_on:
      - godot-server

networks:
  tictactoe_net:
    driver: bridge

volumes:
  godot_data:
